config/routes.rb
Vendiwebapp::Application.routes.draw do

  get "items/index"
  get "welcome/index"

  root 'welcome#index'

  match '/survey-s' => 'survey_pages#resellers', :as => :survey_s, via: [:get]
  match '/survey-o' => 'survey_pages#owners', :as => :survey_o, via: [:get]

  match '/items' => 'items#index', :as => :items, via: [:get]

  match "/profile" => 'user#show', :as => :profile, via: [:get]

  match '/about' => 'welcome#about_us', :as => :about_us, via: [:get]

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  	@items = Item.all
  end
end

app/controllers/survey_pages_controller.rb
class SurveyPagesController < ApplicationController
  def owners
  end

  def resellers
  end


end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def aboutus
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/survey_pages_helper.rb
module SurveyPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/index.html.haml
=provide :title, 'Items'
.container-fluid
	.row
		.col-lg-10.col-lg-offset-1
			.row
				-@items.each do |item|
					.col-lg-3
						#my-carousel.carousel.slide{"data-ride" => "carousel"}
							/ Indicators
							%ol.carousel-indicators
								%li.active{"data-slide-to" => "0", "data-target" => "#carousel-example-generic"}
								%li{"data-slide-to" => "1", "data-target" => "#carousel-example-generic"}
								%li{"data-slide-to" => "2", "data-target" => "#carousel-example-generic"}
							/ Wrapper for slides
							.carousel-inner
								.item.active
									%img{alt: "...", src:image_path("arturo.png")}/
								.item
									%img{alt: "...", src:image_path("arturo.png")}/
								.item
									%img{alt: "...", src:image_path("arturo.png")}/

						%button.btn.item-btn.text-center{align: "center", "data-placement" => "bottom", "data-toggle" => "popover", type: "button"}
							%h1.item-title= item.title
							#popover_content_wrapper{style: "display: none !important"}
								%h3 Description:
								%p= item.description								
								%h3 Tell us at what price you think you can sell this item after fees?
								%form.form-inline{action: ""}
									.form-group
										%label.sr-only{for: "price"} Price submission.
										- placeholder = (item.price.nil? ? "Price" : item.price)
										%input#price.form-control{placeholder: "Price", type: "text"}
										%input.btn.btn-default{type: "submit"}
				

%script
	$(document).ready(function() {

	$('.carousel').carousel({
	interval: 2000
	});

	$('.item-btn').popover({ 
	html : true, 
	content: function() {
	return $('#popover_content_wrapper').html();
	}
	});

	});

app/views/layouts/_footer.html.haml
%footer.page-footer
	%hr.h-line/
	.container-fluid
		.row
			%p.col-sm-6{style: "align: left;"}
				© Vendi Inc. 2014
		
			%p.col-sm-6{style: "text-align: right"}
			-#	=link_to "About us", "#{about_us_path}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default{role: "navigation"}
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %p.navbar-brand
        =link_to "Vendi", "#{root_path}"
    

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title 
			=yield :title
		= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
		= javascript_include_tag "application", "data-turbolinks-track" => true
		= csrf_meta_tags
	%body
		= render 'layouts/navigation'
		= yield
		= render 'layouts/footer' 

app/views/survey_pages/owners.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
    %meta{content: "", name: "description"}/
    %meta{content: "Vendi.Inc", name: "author"}/
    %link{href: "../../assets/ico/favicon.ico", rel: "shortcut icon"}/
    %title Vendi
    / Bootstrap core CSS
    / %link{href: "css/bootstrap.min.css", rel: "stylesheet"}/
    / Custom styles for this template
    / %link{href: "css/jumbotron-narrow.css", rel: "stylesheet"}/
    / Just for debugging purposes. Don't actually copy this line!
    /[if lt IE 9] <script src="../../assets/js/ie8-responsive-file-warning.js"></script>
    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  %body
    .container-fluid
      .jumbotron
        %h1#title Vendi
        %p.lead Hi! We are developing a new product to make the experience of selling your items at home amazing, but we need your help.  Take a couple of minutes to fill out the survey below, so we know what matters to you.  We really value your opinion.  Feel free to contact us if you have any additional feedback or questions at VendiTeam@gmail.com
      #typeform.row-fluid
        .col-md-12
          %iframe{frameborder: "0", src: "http://vendi.typeform.com/to/lNCWyb"}
      .footer
        %p © Vendi 2014
    / /container
    /
      Bootstrap core JavaScript
      \==================================================
    / Placed at the end of the document so the pages load faster

app/views/survey_pages/resellers.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
    %meta{content: "", name: "description"}/
    %meta{content: "Vendi.Inc", name: "author"}/
    /%link{href: "../../assets/ico/favicon.ico", rel: "shortcut icon"}/
    %title Vendi
    / Bootstrap core CSS
    /%link{href: "css/bootstrap.min.css", rel: "stylesheet"}/
    / Custom styles for this template
    /%link{href: "css/jumbotron-narrow.css", rel: "stylesheet"}/
    / Just for debugging purposes. Don't actually copy this line!
    /[if lt IE 9] <script src="../../assets/js/ie8-responsive-file-warning.js"></script>
    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  %body
    .container-fluid
      .jumbotron
        %h1#title Vendi
        %p.lead Hi! We are developing a new product to help individuals make money by selling items online, but we need your help.  Take a couple of minutes to fill out the survey below, so we know what matters to you.  We really value your opinion.  Feel free to contact us if you have any additional feedback or questions at VendiTeam@gmail.com
      #typeform.row-fluid
        .col-md-12
          %iframe{frameborder: "0", src: "http://vendi.typeform.com/to/n3GvfH"}
      .footer
        %p © Vendi 2014
    / /container
    / Bootstrap core JavaScript==================================================
    / Placed at the end of the document so the pages load faster

app/views/user/show.html.haml
%h1 User#show
%p Find me in app/views/user/show.html.haml

app/views/welcome/about_us.html.haml
.container-fluid
	.row 
		.col-lg-4.col-lg-offset-2
			.aboutus
				%img.img-circle{alt: "Arturo", src:image_path("arturo.png")}
				%h1 Jason Clark
				%h2 Co-Founder
				%p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo, deleniti, reiciendis sequi in porro corporis harum autem repellat tempora culpa consequatur distinctio voluptatibus animi ab omnis voluptatum ducimus ipsa sapiente!
		.col-lg-4
			.aboutus
				%img.img-circle{alt: "Arturo", src:image_path("arturo.png")}
				%h1 Arturo Pacifico Griffini
				%h2 Co-Founder
				%p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo, deleniti, reiciendis sequi in porro corporis harum autem repellat tempora culpa consequatur distinctio voluptatibus animi ab omnis voluptatum ducimus ipsa sapiente!

app/views/welcome/index.html.haml
=provide(:title, 'Welcome')
.container-fluid
	.row
		.col-lg-8.col-lg-offset-2
			%h1#title Vendi
			%hr.h-line/
			.about-app
				%p 
					%b Consider the following story:  
					Jordan is busy and has several unwanted items to sell, but doesn’t have the time or inclination to do the selling.  Alex makes a living selling online but searches through yard sales and flea markets struggling to find items to sell.  Enter Vendi. Vendi facilitates the sale of Jordan’s stuff through Alex. Alex makes a commission and Jordan’s stuff gets sold at a fair price; everyone wins.
			%hr.h-line/
			.about-app
				%p 
					%b Our Vision:
					We desire a future where there is little friction in the recycling of goods from one individual to another.  To make this a reality we are simplifying the process of selling one’s unwanted items, while creating income for others.  Lets realize this vision together. 
			%hr.h-line
			.call
				%h2 Which of two experiences are you looking for?

				.col-sm-6.text-center
					%p If you are interested in the reselling experience help us determine what matters to you.
					=button_to "Continue", survey_s_path, {:method => "get", class: "btn btn-primary"}
				.col-sm-6.text-center
					%p If you want help selling your items, help us determine what matters to you. 
					=button_to "Continue", survey_o_path, {:method => "get", class: "btn btn-primary"}
			%hr.h-line
			

	